// This file is auto-generated by Supabase
// You can generate updated types using the Supabase CLI

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Define your database tables here
      // Example:
      // profiles: {
      //   Row: {}
      //   Insert: {}
      //   Update: {}
      // }
    }
    Views: {
      // Define your database views here
    }
    Functions: {
      // Define your database functions here
    }
    Enums: {
      // Define your enums here
    }
  }
}
